#!/usr/bin/env python3
"""Generate src/pvdevinfo.inc from Apple's kernel driver: the key -> field table of parseDeviceInfo (hub-task-446).

parseDeviceInfo(buffer, count, APVDeviceInfoStruct*) walks `count` pairs {u32 key, u32 value}; a jump table (read from the kext in the collection) maps each key
0..0x2c to `value -> struct+offset; struct[definedOffset] = 1` (key 0 and 0x2b: ignored). Field and flag NAMES come from the Metal bundle's `_deviceInfo` ivar type
(tools/m1/objctype.py), which gives the 224-byte layout. Needs ~/work/tools/macos-full. Output: C++ table."""
import os
import re
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, '..', 'm1'))
import pvdis
import objctype
import apvdis

PARSE_JUMP_TABLE = 0x142bd1b8   # in SystemKernelExtensions.kc 25G83: the `lea 0x31c(%rip),%rsi` of parseDeviceInfo (0x142bce85)


def main():
    k = pvdis.kc(pvdis.SKE)
    img = apvdis.Image(apvdis.APV)
    ix = apvdis.Index(img)
    names = {}
    for c in ix.classes:
        if c['name'] == 'AppleParavirtDevice':
            for off, nm, ty, al in c['ivars']:
                if nm == '_deviceInfo':
                    kind, size, align, kids, _ = objctype.parse(ty)
                    assert size == 224, size
                    for name, t2, sz, o in objctype.flatten(kind, size, align, kids):
                        names.setdefault(o, name.lstrip('.'))
    rows = []
    for key in range(0x2d):
        o = k.va2off(PARSE_JUMP_TABLE + 4 * key)
        tgt = PARSE_JUMP_TABLE + struct.unpack('<i', k.d[o:o + 4])[0]
        open('/tmp/pvdis.bin', 'wb').write(pvdis.dump(k, tgt, 16))
        r = subprocess.run(['objdump', '-D', '-b', 'binary', '-mi386:x86-64', '--adjust-vma=0x%x' % tgt, '-M', 'att', '--no-show-raw-insn', '/tmp/pvdis.bin'],
                           capture_output=True, text=True)
        f = d = None
        for l in [x for x in r.stdout.splitlines() if re.match(r'\s*[0-9a-f]+:', x)][:3]:
            m1 = re.search(r'mov\s+%r8d,\s*(0x[0-9a-f]+)?\(%rdx\)', l)
            if m1:
                f = int(m1.group(1) or '0', 16)
            m2 = re.search(r'movb\s+\$0x1,(0x[0-9a-f]+)?\(%rdx\)', l)
            if m2:
                d = int(m2.group(1) or '0', 16)
        if f is not None and d is not None:
            rows.append((key, f, d, names[f]))
    out = ['// Generated by tools/m0/gen-devinfo.py from AppleParavirtGPU\'s parseDeviceInfo jump table (25G83). Do not edit.',
           '// key: the u32 key of a {key, value} pair of the GetDeviceInfo reply; value: offset of the u32 field in the 224-byte APVDeviceInfoStruct;',
           '// defined: offset of the byte the parser sets to 1. Keys 0 and 0x2b (and anything above 0x2c) are ignored by the parser.',
           'static const DeviceInfoKey kDeviceInfoKeys[] = {']
    for key, f, d, n in rows:
        out.append('\t{ 0x%02x, 0x%02x, 0x%02x, "%s" },' % (key, f, d, n))
    out.append('};')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
