#!/usr/bin/env bash
# Build the GPU test kernels in shaders/ for gfx1201 with upstream LLVM's
# AMDGPU backend and emit them as C arrays the kext embeds:
#   shaders/<name>.s   -> src/<name>_kernel.h   raw machine code (llvm-mc)
#   shaders/<name>.cl  -> src/<name>_codeobj.h  a whole code object (clang + ld.lld)
# The generated headers are committed, so building the kext needs no LLVM.
#
#   tools/build-shaders.sh            (LLVM 19+: LLVM=/usr/lib/llvm-19 by default)
set -euo pipefail
cd "$(dirname "$0")/.."
LLVM=${LLVM:-/usr/lib/llvm-19}
mkdir -p build/shaders

# Raw machine code from assembly.
for src in shaders/*.s; do
	name=$(basename "$src" .s)
	"$LLVM/bin/llvm-mc" -triple=amdgcn-amd-amdhsa -mcpu=gfx1201 -filetype=obj \
		-o "build/shaders/$name.o" "$src"
	"$LLVM/bin/llvm-objcopy" -O binary --only-section=.text "build/shaders/$name.o" \
		"build/shaders/$name.bin"
	python3 - "$name" "build/shaders/$name.bin" "src/${name}_kernel.h" "$src" <<'PY'
import sys
name, binf, out, src = sys.argv[1:]
code = open(binf, 'rb').read()
assert len(code) % 4 == 0 and code, 'odd-sized kernel'
dws = [int.from_bytes(code[i:i + 4], 'little') for i in range(0, len(code), 4)]
lines = ['//', f'//  {name}_kernel.h — generated by tools/build-shaders.sh from {src}',
         '//  (llvm-mc -mcpu=gfx1201). Do not edit; edit the .s and regenerate.', '//', '',
         '#pragma once', '#include <stdint.h>', '',
         f'static const uint32_t k{name.capitalize()}Kernel[] = {{']
for i in range(0, len(dws), 4):
    lines.append('\t' + ', '.join(f'0x{d:08x}' for d in dws[i:i + 4]) + ',')
lines += ['};', '']
open(out, 'w').write('\n'.join(lines))
print(f'{out}: {len(dws)} dwords')
PY
done

# Whole code objects from OpenCL C, for the kext's code-object loader.
for src in shaders/*.cl; do
	name=$(basename "$src" .cl)
	"$LLVM/bin/clang" -target amdgcn-amd-amdhsa -mcpu=gfx1201 -x cl -cl-std=CL2.0 -O2 \
		-nogpulib -c "$src" -o "build/shaders/$name.o"
	"$LLVM/bin/ld.lld" -shared "build/shaders/$name.o" -o "build/shaders/$name.hsaco"
	python3 - "$name" "build/shaders/$name.hsaco" "src/${name}_codeobj.h" "$src" <<'PY'
import sys
name, elf, out, src = sys.argv[1:]
data = open(elf, 'rb').read()
lines = ['//', f'//  {name}_codeobj.h — generated by tools/build-shaders.sh from {src}',
         '//  (clang -mcpu=gfx1201, ld.lld -shared). Do not edit; edit the .cl and regenerate.',
         '//', '', '#pragma once', '#include <stdint.h>', '',
         f'static const uint8_t k{name.capitalize()}CodeObject[] = {{']
for i in range(0, len(data), 16):
    lines.append('\t' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',')
lines += ['};', '']
open(out, 'w').write('\n'.join(lines))
print(f'{out}: {len(data)} bytes')
PY
done
