#!/usr/bin/env bash
# Assemble the GPU test kernels in shaders/ for gfx1201 with upstream LLVM's
# AMDGPU backend and emit them as C arrays the kext embeds (src/<name>_kernel.h).
# The generated headers are committed, so building the kext needs no LLVM.
#
#   tools/build-shaders.sh            (LLVM 19+: LLVM=/usr/lib/llvm-19 by default)
set -euo pipefail
cd "$(dirname "$0")/.."
LLVM=${LLVM:-/usr/lib/llvm-19}
MC=$LLVM/bin/llvm-mc
OBJCOPY=$LLVM/bin/llvm-objcopy
mkdir -p build/shaders

for src in shaders/*.s; do
	name=$(basename "$src" .s)
	"$MC" -triple=amdgcn-amd-amdhsa -mcpu=gfx1201 -filetype=obj -o "build/shaders/$name.o" "$src"
	"$OBJCOPY" -O binary --only-section=.text "build/shaders/$name.o" "build/shaders/$name.bin"
	python3 - "$name" "build/shaders/$name.bin" "src/${name}_kernel.h" "$src" <<'PY'
import sys
name, binf, out, src = sys.argv[1:]
code = open(binf, 'rb').read()
assert len(code) % 4 == 0 and code, 'odd-sized kernel'
dws = [int.from_bytes(code[i:i + 4], 'little') for i in range(0, len(code), 4)]
lines = ['//', f'//  {name}_kernel.h — generated by tools/build-shaders.sh from {src}', '//  (llvm-mc -mcpu=gfx1201). Do not edit; edit the .s and regenerate.', '//', '',
         '#pragma once', '#include <stdint.h>', '',
         f'static const uint32_t k{name.capitalize()}Kernel[] = {{']
for i in range(0, len(dws), 4):
    lines.append('\t' + ', '.join(f'0x{d:08x}' for d in dws[i:i + 4]) + ',')
lines += ['};', '']
open(out, 'w').write('\n'.join(lines))
print(f'{out}: {len(dws)} dwords')
PY
done
