//
//  probe_kernel.h — generated by tools/build-shaders.sh from shaders/probe.s
//  (llvm-mc -mcpu=gfx1201). Do not edit; edit the .s and regenerate.
//

#pragma once
#include <stdint.h>

static const uint32_t kProbeKernel[] = {
	0x84038602, 0x4a020003, 0x30040282, 0x16060283,
	0x4a0606ff, 0x5eed0000, 0xee068000, 0x01800000,
	0x00000002, 0xbfb00000,
};
