//
//  pscol_kernel.h — generated by tools/build-shaders.sh from shaders/pscol.s
//  (llvm-mc -mcpu=gfx1201). Do not edit; edit the .s and regenerate.
//

#pragma once
#include <stdint.h>

static const uint32_t kPscolKernel[] = {
	0xbefd0002, 0xbefe1c7e, 0xce8f0002, 0xce8f0103,
	0xce8f0204, 0xcd000205, 0x040a0102, 0xcd000106,
	0x040e0103, 0xcd000007, 0x04120104, 0xcd010705,
	0x04160302, 0xcd010706, 0x041a0303, 0xcd010707,
	0x041e0304, 0x7e1002f2, 0xf800080f, 0x08070605,
	0xbfb00000,
};
