//
//  psred_kernel.h — generated by tools/build-shaders.sh from shaders/psred.s
//  (llvm-mc -mcpu=gfx1201). Do not edit; edit the .s and regenerate.
//

#pragma once
#include <stdint.h>

static const uint32_t kPsredKernel[] = {
	0x7e0002f2, 0x7e020280, 0x7e040280, 0x7e0602f2,
	0xf800080f, 0x03020100, 0xbfb00000,
};
