#!/usr/bin/env python3
"""mkgolden.py <pipegen dp trace> <linux commit> > tools/dp_retime_linux.inc

The register writes Linux makes when it retimes a DisplayPort stream (pipegen's "dp" scenario), as a table
for tools/atomdump.cpp to hold src/modeset.cpp's DisplayPort plan against. Waits, delays and marks are
dropped: the test compares what the registers hold afterwards."""
import sys

lines = [l.split() for l in open(sys.argv[1]) if l.strip()]
cfg = lines[0]
assert cfg[0] == 'CONFIG'
print(f'''// GENERATED by tools/pipegen (run.sh) from Linux {sys.argv[2][:12]}. Do not edit.
// What amdgpu writes to give a lit DisplayPort stream a new timing without touching the link: pipe {cfg[1]},
// DIG{cfg[2]}, {cfg[5]}x{cfg[9]} at {cfg[13]} kHz, with a 720 MHz DP reference clock and four HBR3 lanes.
// { '{' } segment, dword, mask, value { '}' }: reg = (reg & ~mask) | value.''')
n = 0
for p in lines[1:]:
    if p[0] in ('W', 'U'):
        print(f'{{ {p[1]}, {p[2]}, 0x{p[3]}, 0x{p[4]} }},   // {p[7]}')
        n += 1
sys.stderr.write(f'mkgolden: {n} writes\n')
