#!/usr/bin/env python3
"""mktrain.py <linux commit> <kind>:<swing>:<pre>:<pipegen dplink trace> ... > tools/dp_train_linux.inc

What Linux does to bring a DisplayPort link up (pipegen's "dplink" scenario: dp_enable_link_phy and
dp_perform_link_training inside perform_link_training_with_retries), one run per simulated sink, as the
sequence of things src/dptrain.cpp asks of its Io: the transmitter on and off, the training pattern, each
lane's drive, every DPCD transfer with its bytes, and the delays. tools/atomdump.cpp runs DpTrain against the
same sinks and holds its sequence against these.

Register writes are not in it: the pattern is one event (the registers behind it are the device's business),
and so are the transmitter commands."""
import re, sys

commit, runs = sys.argv[1], sys.argv[2:]
TPS = {0: 1, 1: 2, 2: 3, 3: 7}                  # DP_DPHY_TRAINING_PATTERN_SEL -> DPCD TRAINING_PATTERN_SELECT
PART_OF_PATTERN = ('set_link_training_complete', 'enable_phy_bypass_mode', 'disable_prbs_mode', 'setup_panel_mode',
                   'set_dp_phy_pattern_passthrough_mode')
PART_OF_PHY = ('enc1_configure_encoder', 'link_encoder_disable')     # on: lane count to the encoder; off

def events(path):
    lines = [l.rstrip('\n') for l in open(path)]
    first = next(i for i, l in enumerate(lines) if ':action=1:' in l)
    after = next(i for i, l in enumerate(lines) if i > first and l.endswith('; dcn401_link_encoder_setup'))
    last = max(i for i in range(first, after) if lines[i].startswith('MARK  aux:'))
    out, video = [], False
    for l in lines[first:last + 1]:
        p = l.split()
        func = p[-1]
        if p[0] == 'MARK':
            what = p[1]
            m = re.match(r'dmub:transmitter_control:action=(\d+):lanes=(\d+):symclk=(\d+):lane=(\d+):drive=0x([0-9a-f]+)$', what)
            a = re.match(r'aux:([rw]):([0-9a-f]+):([0-9a-f]*)$', what)
            if m and m.group(1) == '1':
                out.append(('X', int(m.group(2)), int(m.group(3)), b''))
            elif m and m.group(1) == '0':
                out.append(('O', 0, 0, b''))
            elif m and m.group(1) == '11':
                out.append(('V', int(m.group(4)), int(m.group(5), 16), b''))
            elif a:
                data = bytes.fromhex(a.group(3))
                assert len(data) <= 6, what
                out.append((a.group(1).upper(), int(a.group(2), 16), len(data), data))
            else:
                sys.exit(f'{path}: unexpected mark {what}')
            video = False
        elif p[0] == 'DELAY':
            out.append(('D', int(p[1]), 0, b''))
        elif func == 'dcn10_link_encoder_set_dp_phy_pattern_training_pattern':
            assert p[0] == 'W'
            out.append(('P', TPS[int(p[4], 16)], 0, b''))
        elif func == 'set_dp_phy_pattern_passthrough_mode':
            if not video:                       # two register updates, one event
                out.append(('P', 0, 0, b''))
            video = True
        elif func not in PART_OF_PATTERN + PART_OF_PHY:
            sys.exit(f'{path}: a register write of {func} inside link training')
    return out

print(f'''// GENERATED by tools/pipegen (run.sh) from Linux {commit[:12]}. Do not edit.
// What amdgpu asks of the hardware and the sink to bring a DisplayPort link up, four lanes at HBR2, against
// simulated sinks that report lock once the lanes are driven the way they ask (voltage swing for clock
// recovery, pre-emphasis for equalisation). Sink kinds: a DPCD 1.4 with TPS4, b DPCD 1.2 with TPS3 and a 4 ms
// reading interval, c DPCD 1.2 with TPS2 only (tools/pipegen/pipegen.c, sink_reset). From the transmitter
// enable to the last DPCD transfer of link training, retries included.
// {{ kind, a, b, data }}: X transmitter on (lanes, symbol clock kHz), O transmitter off, P training pattern on
// the link (0 video, else the DPCD pattern number), V a lane's drive (lane, swing | pre-emphasis << 3),
// W R a DPCD write / read (address, length, bytes), D delay (microseconds).
''')
table = []
for run in runs:
    kind, swing, pre, path = run.split(':', 3)
    ev = events(path)
    name = f'kTrain_{kind}_{swing}_{pre}'
    print(f'static const TrainEvent {name}[] = {{')
    for what, a, b, data in ev:
        hexes = ', '.join(f'0x{x:02x}' for x in data)
        print(f"\t{{ '{what}', 0x{a:x}, {b}, {{ {hexes or '0'} }} }},")
    print('};')
    table.append((kind, swing, pre, name, len(ev)))
    sys.stderr.write(f'mktrain: sink {kind} {swing}/{pre}: {len(ev)} events\n')
print('\nstatic const TrainRun kTrainRuns[] = {')
for kind, swing, pre, name, n in table:
    print(f"\t{{ '{kind}', {swing}, {pre}, {name}, {n} }},")
print('};')
